events {}
http {
    server {
        listen 8080;
        location / {
            proxy_pass http://94.72.121.9:25566;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
